= HiveMQ AWS Cloudwatch Extension


== Purpose

This Extension allows to report HiveMQ metrics to AWS Cloudwatch.

It is possible to send every HiveMQ metric to Cloudwatch. Every metric which should be reported
must be configured explicitly to reduce the costs, since Cloudwatch can be expensive if you
publish too much (unnecessary) data.


[CAUTION]
.AWS Cloudwatch costs
====
AWS Cloudwatch metrics can be *very* expensive. So please make sure you really want to report the specified metrics.
You can find the full AWS pricing https://aws.amazon.com/cloudwatch/pricing/[here].

At the time of writing the AWS prices are the following:

* `$0.50` per custom metric
* `$0.01` per 1000 _GetMetricStatistics_, _ListMetrics_, or _PutMetricData_ requests

====

=== Installation
Unzip the file: `hivemq-cloudwatch-extension-<version>.zip` to the directory: `<HIVEMQ_HOME>/extensions`
. A configuration file `extension-config.xml` can be found in the `hivemq-cloudwatch-extension` folder.
The properties are preconfigured with standard settings and can be adapted to your needs (The meaning of the fields is explained below).
. Start HiveMQ.


== Configuration

The Cloudwatch extension uses its own configuration file 'extension-config.xml'.


=== extension-config.xml

The following properties are available:

|===
| Property | Description

| <reportInterval>
| A value in minutes which sets the reporting interval (defaults to 1 minute)
| <connectionTimeout>
| The connection timeout in ms. The default is the `com.amazonaws.ClientConfiguration.	DEFAULT_CONNECTION_TIMEOUT`
| <metric enabled="{true/false}">
| a metric name (from a list of metrics) which should be reported to Cloudwatch
|===


.Example Configuration
[source]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<extension-configuration>
    <reportInverval>1</reportInverval>
       <connectionTimeout>50</connectionTimeout>
       <metrics>
           <metric>com.hivemq.messages.incoming.total.count</metric>
           <metric>com.hivemq.messages.outgoing.total.count</metric>
           <metric enabled="false">com.hivemq.messages.incoming.total.rate</metric>
       </metrics>
</extension-configuration>
----
A list of all available metrics can be found on the HiveMQ Documentation
here at https://www.hivemq.com/docs/hivemq/4.6/user-guide/monitoring.html#metrics[HiveMQ Metrics]


== Contributing

If you want to contribute to HiveMQ Cloudwatch Extension, see the link:CONTRIBUTING.md[contribution guidelines].

== License

HiveMQ Cloudwatch Extension is licensed under the `APACHE LICENSE, VERSION 2.0`. A copy of the license can be found link:LICENSE[here].


